kind: pipeline
type: docker
name: Staging

steps:
  - name: Build image
    image: docker/compose:1.23.2
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - cd /drone/src/
      - docker build -t colorful:latest .

  - name: Create service
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      #把原本的container 關掉
      - docker-compose -f /drone/src/docker-compose.yml -p backend down
      #重新開啟現在的container
      - docker-compose -f /drone/src/docker-compose.yml -p backend up -d
      # docker rmi 表示移除images $(特定ID), docker images -f "dangling=true" -q 會show出所有tag=<none>的無用images, -q表示顯示 id
      - docker rmi $(docker images -f "dangling=true" -q)

  - name: Cleanup
    image: docker
    commands:
      - docker image rm colorful:latest
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
