version: '3.7'
services:
  redis:
    image: redis
    ports:
      - xxxx:xxxx

  rabbit:
    image: rabbitmq:3-management
    ports:
      - xxxx:xxxx
      - xxxx:xxxx

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - xxxx:xxxx

volumes:
  postgres-data:
